/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "init.h"
#include "fsm.h"

int main(void)
{
    // Configure ARM cortex pheripherals
    systick_init();

    // Initalise all registers using wrapper functions
    initialise_registers();

    /* Loop forever */
	while (1) {

    }
}

// Triggered on rising edge when new item (PA2) is pressed.
void EXTI2_3_IRQHandler() {
    if (EXTI->RPR1 & (1 << 2)) { // check rising edge trigger bit set
        EXTI->RPR1 |= (1 << 2); // clear bit
        if (current_stage == STAGE_0) { // ensure not in sorting stage
            sorting_stage_fsm(); // invoke fsm logic
        }
    } 
}

// Triggered on rising edge when step gate (PA10) or e-stop (PB5) are pressed.
void EXTI4_15_IRQHandler() {
    if (EXTI->RPR1 & (1 << 5)) { // check rising edge trigger bit set for e-stop
        EXTI->RPR1 |= (1 << 5); // clear bit
        current_stage = STAGE_4; // set to binding state (can't leave state)
        sorting_stage_fsm(); // invoke fsm logic
        pin_write(GPIOA, 9, PIN_HIGH); // set fault led high
    } else if (EXTI->RPR1 & (1 << 10)) { // check rising edge trigger bit for step gate
        EXTI->RPR1 |= (1 << 10); // clear bit
        if (current_stage != STAGE_0) { // ensure only in sorting stage
            sorting_stage_fsm(); // invoke fsm logic
        }
    }
}

// Timer 3 interrupt every 20ms to set servo 1 and 2 positions.
void TIM3_IRQHandler() {
    if (TIM3->SR & (1 << 0)) {
        TIM3->SR &= ~(1 << 0); // clear flag
        TIM3->CCR2 = servo_1_pos; // set servo 1 position
        TIM3->CCR3 = servo_2_pos; // set servo 1 position
    }
}
