/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "reset_and_control_clock.h"
#include "interrupt.h"
#include "gpio.h"
#include "stm32c031xx.h"
#include "timer.h"

static volatile uint32_t p2_button = 0;
static volatile uint32_t counter = 0;


int main(void)
{
    enable_port_clock(A);
    init_pin(GPIOA, 2, MODE_INPUT, PULL_DOWN);
    init_pin(GPIOA, 9, MODE_OUTPUT, NONE);
    init_pin(GPIOA, 5, MODE_OUTPUT, NONE);

    enable_interrupt(A, RISING, 2, 1);
    enable_timer(TIM16, 65534, 5000);

    /* Loop forever */
	while (1) {
        if (counter > 0) {
            counter--;
        } else if (p2_button) {
            p2_button = 0;
            pin_write(GPIOA, 9, PIN_LOW);
        }
    }
}

void EXTI2_3_IRQHandler() {

    if (EXTI->RPR1 & (1 << 2)) {
        p2_button = 1;
        counter = 1000000;
        EXTI->RPR1 |= (1 << 2);
        pin_write(GPIOA, 9, PIN_HIGH);
    }
}

void TIM16_IRQHandler() {
    if (TIM16->SR & (1 << 0)) {
        TIM16->SR &= ~(1 << 0);
        toggle_output(GPIOA, 5);
    }
}
